apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: plain-
commonLabels:
  app: plain-app
images:
- name: doody/plain_app
  newTag: latest
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
